# Generated by Django 5.1 on 2024-08-31 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("spam", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="newuser",
            managers=[],
        ),
    ]
