# Generated by Django 5.1 on 2024-08-31 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("spam", "0002_alter_newuser_managers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newuser",
            name="username",
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
